### PR TITLE
Recover ICS support on Chromium 44

### PR DESCRIPTION
**Pull request by lincsoon**
BUG=XWALK-4356

### CODE REVIEW

**Comment by lincsoon** [comment]
@rakuco @halton @axinging @fujunwei Please help to review

**Comment by darktears** [comment]
LGTM but I'll wait the Android folks to double checks. Then someone can merge and roll the DEPS.

**Comment by axinging** [comment]
LGTM.

**Comment by halton** [comment]
@axinging does the comment you asked resolved?

**Comment by axinging** [comment]
@halton, I am just curious why add this. I am ok if merging this.

**Comment by halton** [comment]
> @halton, I am just curious why add this. I am ok if merging this.

Good, I give my LGTM based on your review.

**Comment by darktears** [comment]
Please roll the deps.

**Pull request merged**
