### PR TITLE
Add flag disable_quic_support to conditional disable QUIC support.

### PR DESCRIPTION
**Pull request by halton**
This commit is cherry-picked from PR #212, two upstreamed commits are
removed.

BUG=https://crosswalk-project.org/jira/browse/XWALK-3801
TEST=Build with/without disable_quic_support=1
      build/android/test_runner.py instrumentation --test-apk=XWalkCoreTest --release
SIZE_REDUCED=255k

### CODE REVIEW

**Comment by halton** [comment]
@darktears @rakuco @kenchris

**Comment by rakuco** [comment]
Did you try upstreaming this?

**Comment by halton** [comment]
@rakuco We had discussion with @darktears about the adding build flag to upstream. The feedback is what we're trying to do is opposite with upstream. Upstream deleted several build flags since they forked from WebKit.

**Comment by darktears** [comment]
These are going to be nightmare to maintain :(. Have you tried rebasing Crosswalk lite patches in a separate branch to see how bad this is.

**Comment by halton** [comment]
@darktears I totally understand your concern, I was rebase owner since we're on RT24 project time. Not sure you missed the email, I send out survey https://docs.google.com/a/intel.com/spreadsheets/d/1RJOKGOABE_IhEnnA1RfbFqS95jxY9kV5MX_4rUGG6jE/edit?usp=sharing to let stakeholder to vote. There I give link to show how big is the change.

Actually, this PR is a rebase from current lite branch (crosswalk 10 based), it need effort but not so frighten. This rebase job is always need, either in lite branch or master branch(if we need this in master).

There are following lite branch changes will be back port to master based on the result of survey, most of are for chromium or blink. Lite team can be always responsible for those build flags changes, we can promise that. How about that?

**Comment by darktears** [comment]
I saw but the spreadsheet is biased towards the size gain and nowhere it mentions the size of the patch and potential rebasing cost. Of course people vote blindly not really knowing the consequences.

This kind of patch is fine : https://github.com/crosswalk-project/blink-crosswalk/pull/51 though the gain is very small.

This one is not IMHO. 255k for a lot of complexity.

**Comment by halton** [comment]
Closed as the concern of @darktears

**Pull request closed without merging**
