### PR TITLE
To exclude code of devtools

### PR DESCRIPTION
**Pull request by PeterWangIntel**
@d0ngjun

### CODE REVIEW

**Comment by halton** [comment]
@d0ngjun would you spend time to review it?

**Comment by d0ngjun** [comment]
Add reducing size info.
just a reminder: xwalk repo need to change the compiling flag into disable_devtools also.

**Comment by PeterWangIntel** [comment]
@d0ngjun @halton

**Comment by d0ngjun** [comment]
LGTM

**Pull request merged**
