### PR TITLE
[Blink] WebCL: Remove config.h and ENABLE_WEBCL.

### PR DESCRIPTION
**Pull request by shaoboyan**
This PR resolve XWALK-6200.
1. replace config.h which removed by upstream with "wtf/build_config.h" and resolve some other compile errors.
2. Abandon "Conditional" attributes which removed by upstream and enable WebCL through gyp path. This patch also remove ENABLE_WEBCL macro.

### CODE REVIEW

**Comment by shaoboyan** [comment]
@rakuco @hujiajie PTAL.

**Comment by shaoboyan** [comment]
@Bysmyyr  PTAL

**Comment by Bysmyyr** [comment]
@shaoboyan can you rebase this?

**Comment by shaoboyan** [comment]
@Bysmyyr  I'll try

**Comment by shaoboyan** [comment]
@Bysmyyr  I revert the tmp solution which you submit. PTAL

**Comment by Bysmyyr** [comment]
thanks. I will test this in 2 hours. now I am rebasing master

**Comment by shaoboyan** [comment]
@Bysmyyr since master is crosswalk-19 now , should i modify this pr and push it on master branch ?

**Comment by Bysmyyr** [comment]
@shaoboyan no, as this is m49 specific and master is still m48

**Comment by shaoboyan** [comment]
@Bysmyyr  thx, and since I'm on vacation for Spring Festival through 6th, Feb to 14th Feb, my reply will be a little bit delay.

**Comment by Bysmyyr** [comment]
thats ok. I am now testing this but if something is found, there is no hurry.

**Comment by hujiajie** [comment]
I suggest to update `webclExceptionStackSetter()` in V8ThrowException.cpp to follow changes in `domExceptionStackSetter()` in this rebase.

**Comment by Bysmyyr** [comment]
yep, this needs rebasing

**Comment by shaoboyan** [comment]
I'll re open a PR to resolve some conflicts with next branch

**Pull request closed without merging**
