### PR TITLE
[lite] disable geolocation and geofencing.

### PR DESCRIPTION
**Pull request by heke123**
Reduce 26K with LZMA on. 
Add flag DISABLE_GEO_FEATURES.

### CODE REVIEW

**Comment by heke123** [comment]
@PeterWangIntel  @halton  Please help to review. thanks.

**Comment by PeterWangIntel** [comment]
LGTM

**Comment by halton** [comment]
@heke123 please rebase so that I can merge.

**Comment by heke123** [comment]
@halton  rebase done.

**Pull request merged**
