### PR TITLE
Add gyp flag use_minimum_resources and exclude unnecessary resources

### PR DESCRIPTION
**Pull request by lincsoon**
Remove following resources:
1. Resources for media player control bar, this part is not usually
used, thus it could be overriden by web developers.
2. The ui resources are for aura/views, Android doesn't need it.

This patch is the backport from Crosswalk-lite

BUG=https://crosswalk-project.org/jira/browse/XWALK-3928
TEST=Build with/without flag use_minimum_resources and simple test on XWalkCoreShell.apk
SIZE_REDUCED=44k(Release build on ARM)
(cherry picked from commit eaacec2898e7f7f4764dd9ea320638b410e4ea07)

### CODE REVIEW

**Comment by lincsoon** [comment]
This PR fixes https://crosswalk-project.org/jira/browse/XWALK-4756

**Comment by lincsoon** [comment]
@rakuco @halton

**Comment by halton** [comment]
code LGTM, not sure whether we need leave the "conflits" part in log. @rakuco what's your option?

**Comment by rakuco** [comment]
Have you checked if the size measurements are still valid? The reason the conflicts were there is because a lot of files were moved to a different directory/grd file, so if you're only editing the previous one it's possible that the size benefit is smaller, to the point where it isn't worth it keeping this commit around.

**Comment by lincsoon** [comment]
Thanks for your remind! The shinked size has changed from 212k to 44k.

@halton Please evaluate if we should keep thie commit

**Comment by halton** [comment]
I think we need investigate how to get back the ~200k.

**Comment by lincsoon** [comment]
So do you agree to suspend this pull request and skip this feature in the next branch temporarily? Since this is not the core feature, I thinks it's better not to have this issue block current branching.

**Comment by halton** [comment]
Yes, i agree.

**Pull request closed without merging**
