### PR TITLE
Web-Video-related resources should be controled by 'disable_web_video'

### PR DESCRIPTION
**Pull request by PeterWangIntel**
It causes the problem of lost 'Play' button in Video Element.

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton

**Comment by heke123** [comment]
LGTM

**Comment by heke123** [comment]
it's trivial, but how about replace "ifndef" by "if ! defined"?  just follow the exist styles.

**Comment by PeterWangIntel** [comment]
ok, it'll be updated soon. thx.

**Comment by PeterWangIntel** [comment]
@heke123

**Comment by heke123** [comment]
LGTM

**Pull request merged**
