### PR TITLE
WebCL: Import OpenCL headers into chromium-crosswalk.

### PR DESCRIPTION
**Pull request by rakuco**
With M49, the WebCL code is always being built, so we need the OpenCL
headers here for pure chromium-crosswalk content_shell builds to work,
since they do not check out Crosswalk and pull its dependencies.

BUG=XWALK-6661

### CODE REVIEW

**Comment by rakuco** [comment]
@shaoboyan @hujiajie

**Comment by shaoboyan** [comment]
LGTM, thx.

**Comment by hujiajie** [comment]
Hi @rakuco, since I'm not quite familiar with the buildbot and gclient, can you explain the following questions:
1. Will the coding style be checked in the future after they get merged? If the answer is no, then it LGTM.
2. I suppose crosswalk.git will be updated with two commits in order later: a) roll chromium-crosswalk (say the commit id in crosswalk.git is abc1234); b) remove the opencl header entry in DEPS.xwalk (def5678). Then if some one is trying to sync crosswalk@abc1234, will these headers conflict with the residual entry in DEPS.xwalk?
3. Will .git in src/third_party/khronos/CL be removed automatically after commit def5678?

Thanks

**Comment by rakuco** [comment]
> 1. Will the coding style be checked in the future after they get merged? If the answer is no, then it LGTM.

The coding style is checked whenever a patch touches a certain file. With our current infrastructure, it means the style checker will complain if we ever change those headers again. This is less than ideal, so I've decided to work on XWALK-1853 and replace the current style checker with {{PRESUBMIT.py}}.

> 2. I suppose crosswalk.git will be updated with two commits in order later: a) roll chromium-crosswalk (say the commit id in crosswalk.git is abc1234); b) remove the opencl header entry in DEPS.xwalk (def5678). Then if some one is trying to sync crosswalk@abc1234, will these headers conflict with the residual entry in DEPS.xwalk?
> 3. Will .git in src/third_party/khronos/CL be removed automatically after commit def5678?

There will be a single commit in Crosswalk doing both a) and b). depot_tools should take care of everything automatically (it will first remove the `src/third_party/khronos/CL` git checkout and then its contents will be readded when chromium-crosswalk is updated).

**Comment by hujiajie** [comment]
LGTM. Thanks

**Pull request merged**
