### PR TITLE
Allow universal access from file if flag is set and url is file scheme.

### PR DESCRIPTION
**Pull request by huningxin**
BUG=449075
TEST=content_unittests --gtest_filter=NavigationControllerTest.IsInPageNavigation

Review URL: https://codereview.chromium.org/855883002

Cr-Commit-Position: refs/heads/master@{#313051}
(cherry picked from commit 3d426436e10135a99f5e54fe1135767eb55712db)

### CODE REVIEW

**Comment by huningxin** [comment]
Backport from upstream to fix crosswalk bug https://crosswalk-project.org/jira/browse/XWALK-3344.

**Comment by huningxin** [comment]
@darktears @rakuco , please take a look. Thanks!

**Comment by darktears** [comment]
Sure, I see no problem with the backport, can you motivate the need?

**Comment by huningxin** [comment]
Sure. Mobile Chrome Apps and Cordova 4.0 upstream relies on setting "allow-universal-access-from-file" flag via Crosswalk embedding API to do cross-origin in-page-navigation. However Chromium has a issue https://code.google.com/p/chromium/issues/detail?id=449075 that will kill the renderer process (kill Crosswalk Android as it is using single process model) when see cross-origin in-page-navigation even if the "allow-universal-access-from-file" is set. This bug blocks Mobile Chrome Apps and Cordova 4.0 upstream to use Crosswalk 10/11/12. This patch fixes that issue.

**Pull request merged**
