### PR TITLE
[Lite] To disable Web Bluetooth

### PR DESCRIPTION
**Pull request by PeterWangIntel**
Disabled size = 20K

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton

**Comment by heke123** [comment]
@PeterWangIntel , Only one comment: 
There are many files in /device directory, and they are compiled. Just make sure they are not linked into the libxwalkcore.so.

**Comment by PeterWangIntel** [comment]
@heke123 
thx for reminding. patch has been updated.

**Comment by heke123** [comment]
LGTM

**Pull request merged**
