### PR TITLE
[Backport]Don't discard navigations.

### PR DESCRIPTION
**Pull request by axinging**
The webview should exist, and the check here dates back to cl/4512195 and cl/4490537 in 2007. There isn't much of a good rationale for it, and we're trying to eliminate dropped navigations, as they make things hard to reason about.

BUG=none
TEST=no changes

Review URL: https://codereview.chromium.org/1179003003

Cr-Commit-Position: refs/heads/master@{#334901}
(cherry picked from commit 0cc28d23f903b48c9f0c0f00c67dd5e1adf5c9e1)
BUG=XWALK-4378

### CODE REVIEW

**Comment by axinging** [comment]
@rakuco  @halton @lincsoon @kenchris @darktears

**Comment by halton** [comment]
@axinging Thanks for the backport, you need add [Backport] prefix so that we can remove it in next rebase cycle. And could you explain how critical w/o this backport? Is there any XWALK bug reported?

**Comment by axinging** [comment]
@halton  BUG=XWALK-4378. Please check the comment

**Comment by halton** [comment]
LGTM

**Comment by lincsoon** [comment]
LGTM

**Comment by rakuco** [comment]
Please remember to roll `DEPS.xwalk`.

**Pull request merged**
