### PR TITLE
Revert AudioDestinationNode.devicePosition commits

### PR DESCRIPTION
**Pull request by rakuco**
This reverts the following commits:
- 2b2cbc8c ("[Windows] Implementation of 'AudioDestinationNode.devicePosition' attribute")
- 43d41bf6 ("Fix calling of AudioOutputStream::AudioSourceCallback API")
- fd8c95a5 ("Remove unused private field device_position_")

This code was added when Crosswalk was being used as an alternative
implementation for some changes to the WebAudio spec:
- https://github.com/WebAudio/web-audio-api/issues/12
- https://github.com/WebAudio/web-audio-api/pull/754

The spec has since been changed and upstream Chromium is being adapted,
so there is no need to keep these patches in Crosswalk any longer.

Additionally, this code in its present form has caused serious
regressions in WebRTC support (the WebRTC Crosswalk sample did not
produce any sound).

Thanks to Michael Walton (mike@farsouthnet.com) for the investigation
leading to this commit.

RELATED BUG=XWALK-7030
RELATED BUG=XWALK-7225

### CODE REVIEW

**Comment by rakuco** [comment]
@darktears @pozdnyakov

**Comment by pozdnyakov** [comment]
lgtm

**Comment by gunsline2** [comment]
When this fix will be at Crosswalk? And witch version of crosswalk will be at.

**Comment by rakuco** [comment]
The fixes were made to master (23.52.579.0), crosswalk-22 (22.52.561.3) and crosswalk-21 (21.51.546.7). The fix to Crosswalk 21 is already available, and the others will be built later today.

**Comment by jasas17** [comment]
so there is no fix for #12 in crosswalk release 23 or any earlier version, because crosswalk 23 relies on chromium version 53?
Is that right or did I miss something?

**Comment by rakuco** [comment]
It depends on when the changes for that web-audio bug were landed in Chromium. Crosswalk 23 relies on Chromium 52, so if the required bits were committed in any later milestone they are not available in Crosswalk.

**Comment by jasas17** [comment]
Thanks for your quick answer,

i followed the discussion on
https://github.com/WebAudio/web-audio-api/issues/12 and was confident, that
support for AudioContext.getOutputTimestamp() will be avalible in crosswalk
soon. But then i read that crosswalk is not maintained anymore. This was
the intention of my previous question.

with best regards


2017-05-08 17:09 GMT+02:00 Raphael Kubo da Costa <notifications@github.com>:

**Pull request merged**
