### PR TITLE
update from oirgin

### PR DESCRIPTION
**Pull request by hgl888**

### CODE REVIEW

**Comment by halton** [comment]
@hgl888 can I know what u are trying to do? Close and reopen meaningless PR back and force.

**Comment by hgl888** [comment]
I try to merge code, but always failed

**Comment by baleboy** [comment]
@hgl888 only committers can merge code in the crosswalk repository, you probably want to work in your own fork

**Comment by halton** [comment]
@hgl888 please be familiar with how github PR working, you have made lots of noises.

**Pull request closed without merging**
