### PR TITLE
[Blink] WebCL: Remove config.h and ENABLE_WEBCL.

### PR DESCRIPTION
**Pull request by shaoboyan**
This PR resolve XWALK-6200.
1. replace config.h which removed by upstream with "wtf/build_config.h" and resolve some other compile errors.
2. Abandon "Conditional" attributes which removed by upstream and enable WebCL through gyp. This patch also removed ENABLE_WEBCL macro.

### CODE REVIEW

**Comment by shaoboyan** [comment]
@rakuco @Bysmyyr @hujiajie PTAL

**Comment by shaoboyan** [comment]
@Bysmyyr, I've fixed the compile problem. Build without -Denable_webcl=1 on linux won't cause any compile error. And WebCL will be enabled only by -Denable_webcl=1 on linux. Pls have a try.

**Comment by Bysmyyr** [comment]
Morning, testing now, thanks. 

ps. you do not need new pr, just force push to that previous

**Comment by Bysmyyr** [comment]
hi, I found build errror:

`bysmyyr:crosswalk> nice -n 19 ninja -j 6 -C src/out/Release xwalk_builder
ninja: Entering directory `src/out/Release'
[3844/4092] CXX obj/third_party/WebKit/Source/modules/webcl/modules.WebCLKernelArgInfoProvider.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/WebKit/Source/modules/webcl/modules.WebCLKernelArgInfoProvider.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=255169-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DGL_GLEXT_PROTOTYPES -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DENABLE_LAYOUT_UNIT_IN_INLINE_BOXES=0 -DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DENABLE_INPUT_MULTIPLE_FIELDS_UI=1 -DWTF_USE_ICCJPEG=1 -DWTF_USE_QCMSLIB=1 -DWTF_USE_WEBAUDIO_FFMPEG=1 -DWTF_USE_DEFAULT_RENDER_THEME=1 -DENABLE_WEBCL=1 -DSK_SUPPORT_GPU=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../.. -I../../skia/config -I../../third_party/WebKit/Source -I../../third_party/khronos -I../../gpu -Igen/angle -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/zlib -I../../third_party/WebKit -Igen/blink -I../../third_party/libpng -I../../third_party/libwebp -I../../third_party/ots/include -I../../third_party/iccjpeg -I../../third_party/libjpeg_turbo -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/qcms/src -I../../v8/include -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Xclang -load -Xclang /home/bysmyyr/crosswalk/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -fcolor-diagnostics -B/home/bysmyyr/crosswalk/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wfor-loop-analysis -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wglobal-constructors -Xclang -load -Xclang /home/bysmyyr/crosswalk/src/third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -Xclang -add-plugin -Xclang blink-gc-plugin -pthread -I/home/bysmyyr/crosswalk/src/build/linux/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I/home/bysmyyr/crosswalk/src/build/linux/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -m64 -march=x86-64 --sysroot=/home/bysmyyr/crosswalk/src/build/linux/debian_wheezy_amd64-sysroot -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11  -c ../../third_party/WebKit/Source/modules/webcl/WebCLKernelArgInfoProvider.cpp -o obj/third_party/WebKit/Source/modules/webcl/modules.WebCLKernelArgInfoProvider.o
../../third_party/WebKit/Source/modules/webcl/WebCLKernelArgInfoProvider.cpp:33:19: error: comparison of unsigned expression >= 0 is always true [-Werror,-Wtautological-compare]
    return (start >= 0 && string[start + 1] == '_' && string[start] == '_');
            ~~~~~ ^  ~
1 error generated.
[3844/4092] CXX obj/third_party/WebKit/Source/bindings/modules/v8/custom/modules.V8DeviceMotionEventCustom.o
ninja: build stopped: subcommand failed.
`

**Comment by Bysmyyr** [comment]
that repull did not change anything?

**Comment by shaoboyan** [comment]
@Bysmyyr  No, it changes, since last time it is a compile error which lacks of files . But this time, as you can see, this is a warning error, you can use -DWerror= . However when build webcl on android platfrom with gcc thiis error wouldn't occur. However, I'll fix this warning if you wish

**Comment by rakuco** [comment]
Well, the compiler warning/error does point to an actual mistake that should be fixed.

**Comment by shaoboyan** [comment]
@rakuco @Bysmyyr  Sorry for the explain about Warning error and as @rakuco said, it is indeed a potential bug. Thx for you guidance. Now the patch is clean without -DWerror= flag.

**Comment by hujiajie** [comment]
WebCLCommandQueue.cpp calls `postTask()` too, so theoretically WebTaskRunner.h should be included there for more more uniform coding style.

**Comment by shaoboyan** [comment]
@hujiajie done.

**Comment by Bysmyyr** [comment]
ok, thanks, lets try

**Comment by Bysmyyr** [comment]
@shaoboyan now it builds fine. I will merge after you fix that whitespace

**Comment by shaoboyan** [comment]
@Bysmyyr thx.

**Comment by hujiajie** [comment]
All C++ changes LGTM, but changes in gyp does not seem to be perfect yet, especially due to the use of modules_idl_files_list.tmp and multiple `enable_webcl` declarations. I need more time to understand how gyp works before the merge if there's no hurry.

**Comment by Bysmyyr** [comment]
make a new pullrequest which reverts those and adds them again fixed when you have something better but use these for now...

Thanks for everybody for efforts this far

**Pull request merged**
